name: E2E2-multiple
on: [push]
jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Setup job done!"
  build:
    needs: setup
    runs-on: ubuntu-18.04
      steps:
        - run: echo "Build job done!"
  test:
    needs: build
    runs-on: ubuntu-18.04
      steps:
        - run: echo "Test job done!"
